name: CI

on:
  push:
    branches:
    - deploy-firebase-develop

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run-script build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy -P makerskills-develop --only hosting,firestore:rules
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
